### ISSUE TITLE
Released version is not on the public branch

### ISSUE THREAD

**Issue by ralphlange** [Cosylab/nds3#1]
The released version, tagged "GPL-Beta-3.0.2", is not part of the default "public" branch.

This leads to the confusing situation that checking out the default branch produces a version that is under the Cosylab restricted license, which is AFAIK not intended.

**Comment by MPavleski** [comment]
Good catch. We'll update the license to GPL3. 

Thank you.

**Comment by ralphlange** [comment]
The update is already in the repo (check the commit with the tag). It's just not part of the "public" branch yet.

**Comment by NickeZ** [comment]
I merged the gpl switch commit in master, removed the "public" branch and switched to using master as the main branch
