### ISSUE TITLE
Please review include file structure

### ISSUE THREAD

**Issue by ralphlange** [Cosylab/nds3#2]
Throughout the code, include files are used like this:
```
#include "../include/nds3/pvBaseIn.h"
#include "../include/nds3impl/pvBaseInImpl.h"
```
IMO, this is really bad, non-portable, and against all conventions and common usage.
It does not allow proper installation of includes in common locations (e.g. when building system packages).

**Comment by ralphlange** [comment]
Questions:
Should the tag be `nds` or `nds3`?
Are the implementation headers public or private (only used for the framework itself)?

The usual way to use such scoped header files would be like
```
#include "nds3/pvBaseIn.h"
```
to allow subdirectory use without having to add all subdirectories to the include path - that is crucial when installing from packages.

**Comment by MPavleski** [comment]
Thanks Ralph. I agree, the headers situation should be fixed. If you already have a fix, please send patches, otherwise I will ask Paolo to fix this.

**Comment by ralphlange** [comment]
I have a fix and will submit a PullRequest - stay tuned.

**Comment by ralphlange** [comment]
I also removed the two separate header name spaces for `nds3` and `nds3impl`, merging everything into `nds3`.

The implementation header files are all called `*Impl.h`, so there are no name clashes, and both the API and the implementation really belong to the same module and namespace, `nds3`. Keep it simple.

**Comment by pbrandoli** [comment]
I think that the include files in the nds3 namespace should stay separate from the rest; they are the only files needed to develop an NDS3 IOCs. None of the include files in nds3 need any include file from nds3impl.

The include files in nds3impl expose implementation details that if used by an IOC would prevent the possibility of swapping NDS3 versions without recompiling the IOC itself.

**Comment by ralphlange** [comment]
I tried to package only the `nds3` headers for the -devel package - that
fails, because the epics support - in your original module layout, this is
the IOC - needs implementation headers.

Which contradicts your statement, doesn't it?

**Comment by ralphlange** [comment]
Generally, I agree that implementation headers should be separate from the public headers.

However, this does not require them to be in a separate directory. Not being packaged in the -devel package would be enough.
If you really prefer a separate directory, the appropriate place would be a subdirectory of `nds3`, e.g. `nds3/impl`. That would still make them an obvious part of the `nds3` headers instead of a separate module.

**Comment by pbrandoli** [comment]
IOC: I used the wrong term. The implementation headers are needed to build the Epics and the Tango layers but are not needed to build the device support.

I agree with you that they could be in a subfolder of NDS3 and that the general include structure should be updated.

**Comment by ralphlange** [comment]
Any IOC that simply uses nds and plugins/drivers (compiled in separate modules) will not need any headers.
Any module that produces nds plug-ins or drivers will need the API headers and the implementation headers.

Within the EPICS scope, there is no case where an application would only need the public API headers. It's always both or none.
However, when nds is used in a compiled application (not an EPICS IOC), there is a use case for API-headers only, I agree.

I will update my PR (in preparation) to use `nds3/impl` for the implementation headers.
I will also change the packaging and create two header packages, nds3-devel (public) and nds3-core-devel (implementation).

**Comment by ralphlange** [comment]
NB: I will not be able to work on this next week, please be patient. :-)

**Comment by ralphlange** [comment]
I agree that devices only need the API headers. My fault, sorry.
So it really does make sense to have two header packages. Will do.

**Comment by NickeZ** [comment]
This is fixed. Thanks!
